namespace GTA5Core.RAGE.Vehicles;

public static class VehicleHash
{
    /// <summary>
    /// 0 当前分类: 小型汽车
    /// </summary>
    public static readonly Dictionary<string, string> Compacts = new()
    {
        { "asbo", "麦克斯韦 反社会" },
        { "blista", "丁卡 旅行家" },
        { "brioso", "古罗帝 精力霸 R/A" },
        { "brioso2", "古罗帝 精力霸 300" },
        { "brioso3", "古罗帝 精力霸 300 宽体版" },
        { "club", "毕福 俱乐部" },
        { "dilettante", "卡林 半吊子" },
        { "dilettante2", "卡林 半吊子" },
        { "issi2", "威尼 天威" },
        { "issi3", "威尼 天威经典版" },
        { "issi4", "威尼 末日天威" },
        { "issi5", "威尼 科幻天威" },
        { "issi6", "威尼 梦魇天威" },
        { "kanjo", "丁卡 旅行家羽黑" },
        { "panto", "贝飞特 哑剧" },
        { "prairie", "包洛坎 原野行者" },
        { "rhapsody", "绝致 狂想曲" },
        { "weevil", "毕福 象鼻虫" },
    };

    /// <summary>
    /// 1 当前分类: 轿车
    /// </summary>
    public static readonly Dictionary<string, string> Sedans = new()
    {
        { "asea", "绝致 海致" },
        { "asea2", "绝致 海致" },
        { "asterope", "卡林 爱硕普" },
        { "cinquemila", "兰帕达缇 五千" },
        { "cog55", "埃努斯 至尊慧眼 55" },
        { "cog552", "埃努斯 至尊慧眼 55（装甲版）" },
        { "cognoscenti", "埃努斯 至尊慧眼" },
        { "cognoscenti2", "埃努斯 至尊慧眼（装甲版）" },
        { "deity", "埃努斯 神灵" },
        { "emperor", "亚班尼 皇霸天" },
        { "emperor2", "亚班尼 皇霸天" },
        { "emperor3", "亚班尼 皇霸天" },
        { "fugitive", "雪佛 流星" },
        { "glendale", "贝飞特 格伦戴尔" },
        { "glendale2", "贝飞特 格伦戴尔改装版" },
        { "ingot", "福狮 英卡特" },
        { "intruder", "卡林 入侵者" },
        { "limo2", "贝飞特 武装礼车" },
        { "premier", "绝致 统领" },
        { "primo", "亚班尼 初代" },
        { "primo2", "亚班尼 初代改装版" },
        { "regina", "敦追里 女皇" },
        { "rhinehart", "绝品 莱茵哈特" },
        { "romero", "烈火马 钢骨灵车" },
        { "schafter2", "贝飞特 莎夫特" },
        { "schafter5", "贝飞特 莎夫特 V12（装甲版）" },
        { "schafter6", "贝飞特 长轴莎夫特（装甲版）" },
        { "stafford", "埃努斯 斯塔福德" },
        { "stanier", "威皮 史塔尼亚" },
        { "stratum", "赛柯尼 地层先锋" },
        { "stretch", "敦追里 加长型礼车" },
        { "superd", "埃努斯 金钻耀星" },
        { "surge", "雪佛 奔腾" },
        { "tailgater", "奥北 密探" },
        { "tailgater2", "奥北 密探 S" },
        { "warrener", "福狮 守护星" },
        { "warrener2", "福狮 守护星 HKR" },
        { "washington", "亚班尼 华盛顿" },
    };

    /// <summary>
    /// 2 当前分类: SUV
    /// </summary>
    public static readonly Dictionary<string, string> SUVs = new()
    {
        { "astron", "菲斯特 宇航" },
        { "baller", "悠游 行者" },
        { "baller2", "悠游 行者" },
        { "baller3", "悠游 行者 LE" },
        { "baller4", "悠游 长轴行者 LE" },
        { "baller5", "悠游 行者 LE（装甲版）" },
        { "baller6", "悠游 长轴行者 LE（装甲版）" },
        { "baller7", "悠游 行者 ST" },
        { "bjxl", "卡林 碧杰 XL" },
        { "cavalcade", "亚班尼 骑兵" },
        { "cavalcade2", "亚班尼 骑兵" },
        { "contender", "威皮 争夺者" },
        { "dubsta", "贝飞特 迪布达" },
        { "dubsta2", "贝飞特 迪布达" },
        { "fq2", "深水 FQ 2" },
        { "granger", "绝致 屌王" },
        { "granger2", "绝致 屌王 3600LX" },
        { "gresley", "冒险家 情欲猎手" },
        { "habanero", "皇霸天 哈拔尼禄" },
        { "huntley", "埃努斯 亨特利 S" },
        { "issi8", "威尼 天威拉力" },
        { "iwagen", "奥北 爱瓦根" },
        { "jubilee", "埃努斯 吉伯力" },
        { "landstalker", "敦追里 追捕者" },
        { "landstalker2", "敦追里 追捕者 XL" },
        { "mesa", "卡尼斯 炎魔" },
        { "mesa2", "卡尼斯 炎魔" },
        { "novak", "兰帕达缇 诺瓦克" },
        { "patriot", "巨象 爱国者" },
        { "patriot2", "巨象 爱国者加长型" },
        { "radi", "威皮 辐光" },
        { "rebla", "绝品 瑞巴 GTS" },
        { "rocoto", "奥北 小辣椒" },
        { "seminole", "卡尼斯 陆上专家" },
        { "seminole2", "卡尼斯 陆上专家边境" },
        { "serrano", "贝飞特 瑟雷诺" },
        { "squaddie", "巨象 列兵" },
        { "toros", "佩嘉西 奔牛" },
        { "xls", "贝飞特 XLS" },
        { "xls2", "贝飞特 XLS(装甲版)" },
    };

    /// <summary>
    /// 3 当前分类: 轿跑车
    /// </summary>
    public static readonly Dictionary<string, string> Coupes = new()
    {
        { "cogcabrio", "埃努斯 至尊慧眼敞篷版" },
        { "exemplar", "浪子 典范" },
        { "f620", "欧斯洛 F620" },
        { "felon", "兰帕达缇 恶龙" },
        { "felon2", "兰帕达缇 恶龙 GT" },
        { "jackal", "欧斯洛 胡狼" },
        { "kanjosj", "丁卡 羽黑 SJ" },
        { "oracle", "绝品 先知 XS" },
        { "oracle2", "绝品 先知" },
        { "postlude", "丁卡 后奏" },
        { "previon", "卡林 普莱温" },
        { "sentinel", "绝品 卫士 XS" },
        { "sentinel2", "绝品 卫士" },
        { "windsor", "埃努斯 温莎" },
        { "windsor2", "埃努斯 温莎敞篷版" },
        { "zion", "绝品 绝品天堂" },
        { "zion2", "绝品 绝品天堂敞篷版" },
    };

    /// <summary>
    /// 4 当前分类: 肌肉车
    /// </summary>
    public static readonly Dictionary<string, string> Muscle = new()
    {
        { "blade", "威皮 刀锋" },
        { "broadway", "卡拉斯科 百老汇" },
        { "buccaneer", "亚班尼 风流海盗" },
        { "buccaneer2", "亚班尼 风流海盗改装版" },
        { "buffalo4", "冒险家 猛牛 STX" },
        { "chino", "威皮 奇诺" },
        { "chino2", "威皮 奇诺改装版" },
        { "clique", "威皮 克里克" },
        { "coquette3", "非凡 艳妇黑鳍" },
        { "deviant", "赛乐斯特 异类" },
        { "dominator", "威皮 公路霸者" },
        { "dominator2", "威皮 尿汤啤公路霸者" },
        { "dominator3", "威皮 公路霸者 GTX" },
        { "dominator4", "威皮 末日公路霸者" },
        { "dominator5", "威皮 科幻公路霸者" },
        { "dominator6", "威皮 梦魇公路霸者" },
        { "dominator7", "威皮 公路霸者 ASP" },
        { "dominator8", "威皮 公路霸者 GTT" },
        { "dukes", "英庞提 公爵" },
        { "dukes2", "英庞提 死亡公爵" },
        { "dukes3", "英庞提 比特公爵" },
        { "ellie", "威皮 爱利" },
        { "eudora", "威拉德 尤朵拉" },
        { "faction", "威拉德 宗派" },
        { "faction2", "威拉德 宗派改装版" },
        { "faction3", "威拉德 宗派改装巨轮版" },
        { "gauntlet", "冒险家 铁腕" },
        { "gauntlet2", "冒险家 红木烟业铁腕" },
        { "gauntlet3", "冒险家 铁腕经典版" },
        { "gauntlet4", "冒险家 铁腕地狱火" },
        { "gauntlet5", "冒险家 铁腕经典改装版" },
        { "greenwood", "冒险家 格林伍德" },
        { "hermes", "亚班尼 赫耳墨斯" },
        { "hotknife", "威皮 热情使徒" },
        { "hustler", "威皮 赫斯勒" },
        { "impaler", "绝致 刺刑官" },
        { "impaler2", "绝致 末日刺刑官" },
        { "impaler3", "绝致 科幻刺刑官" },
        { "impaler4", "绝致 梦魇刺刑官" },
        { "imperator", "威皮 末日凯撒大帝" },
        { "imperator2", "威皮 科幻凯撒大帝" },
        { "imperator3", "威皮 梦魇凯撒大帝" },
        { "lurcher", "亚班尼 闹鬼灵车" },
        { "manana2", "亚班尼 明日之星改装版" },
        { "moonbeam", "绝致 月光" },
        { "moonbeam2", "绝致 月光改装版" },
        { "nightshade", "英庞提 暗夜魅影" },
        { "peyote2", "威皮 佩优特古董赛车" },
        { "phoenix", "英庞提 不死鸟" },
        { "picador", "雪佛 斗牛士" },
        { "ratloader", "老爷卡车" },
        { "ratloader2", "冒险家 老爷货车" },
        { "ruiner", "英庞提 灭世暴徒" },
        { "ruiner2", "英庞提 灭世暴徒 2000" },
        { "ruiner3", "英庞提 灭世暴徒" },
        { "ruiner4", "英庞提 灭世暴徒 ZZ-8" },
        { "sabregt", "绝致 军刀涡轮" },
        { "sabregt2", "绝致 军刀涡轮改装版" },
        { "slamvan", "威皮 大满贯皮卡" },
        { "slamvan2", "威皮 失落摩托帮大满贯皮卡" },
        { "slamvan3", "威皮 大满贯皮卡改装版" },
        { "slamvan4", "威皮 末日大满贯皮卡" },
        { "slamvan5", "威皮 科幻大满贯皮卡" },
        { "slamvan6", "威皮 梦魇大满贯皮卡" },
        { "stalion", "绝致 种马" },
        { "stalion2", "绝致 吃得饱汉堡种马" },
        { "tahoma", "绝致 塔霍马轿跑车" },
        { "tampa", "绝致 坦帕" },
        { "tampa3", "绝致 武装坦帕" },
        { "tulip", "绝致 郁金" },
        { "tulip2", "绝致 郁金 M-100" },
        { "vamos", "绝致 瓦魔狮" },
        { "vigero", "绝致 活力够" },
        { "vigero2", "绝致 活力够 ZX" },
        { "virgo", "亚班尼 室女座" },
        { "virgo2", "敦追里 经典室女座改装版" },
        { "virgo3", "敦追里 经典室女座" },
        { "voodoo", "绝致 巫毒改装版" },
        { "voodoo2", "绝致 巫毒" },
        { "weevil2", "毕福 象鼻虫改装版" },
        { "yosemite", "绝致 约塞米蒂" },
        { "yosemite2", "绝致 漂移约塞米蒂" },
    };

    /// <summary>
    /// 5 当前分类: 经典跑车
    /// </summary>
    public static readonly Dictionary<string, string> SportsClassics = new()
    {
        { "ardent", "欧斯洛 炽焰" },
        { "btype", "亚班尼 罗斯福" },
        { "btype2", "亚班尼 科学怪人" },
        { "btype3", "亚班尼 罗斯福勇气" },
        { "casco", "兰帕达缇 卡斯科" },
        { "cheburek", "卢恩 切布列克" },
        { "cheetah2", "古罗帝 猎豹经典版" },
        { "coquette2", "非凡 艳妇经典版" },
        { "deluxo", "英庞提 德罗索" },
        { "dynasty", "威尼 王朝" },
        { "fagaloa", "福狮 法加洛亚" },
        { "feltzer3", "贝飞特 斯特林 GT" },
        { "gt500", "古罗帝 GT500" },
        { "infernus2", "佩嘉西 炼狱魔经典版" },
        { "jb700", "浪子 JB 700" },
        { "jb7002", "浪子 JB 700W" },
        { "mamba", "绝致 曼巴" },
        { "manana", "亚班尼 明日之星" },
        { "michelli", "兰帕达缇 米其利 GT" },
        { "monroe", "佩嘉西 门罗" },
        { "nebula", "福狮 星云涡轮" },
        { "peyote", "威皮 佩优特" },
        { "peyote3", "威皮 佩优特改装版" },
        { "pigalle", "兰帕达缇 皮卡乐" },
        { "rapidgt3", "浪子 疾速 GT 经典版" },
        { "retinue", "威皮 随行者" },
        { "retinue2", "威皮 随行者 Mk 2" },
        { "savestra", "爱尼仕 萨维斯特拉" },
        { "stinger", "古罗帝 史汀格" },
        { "stingergt", "古罗帝 史汀格 GT" },
        { "stromberg", "欧斯洛 斯特龙伯格" },
        { "swinger", "欧斯洛 放荡者" },
        { "toreador", "佩嘉西 图拉尔多" },
        { "torero", "佩嘉西 斗牛" },
        { "tornado", "绝致 龙卷风" },
        { "tornado2", "绝致 龙卷风" },
        { "tornado3", "绝致 龙卷风" },
        { "tornado4", "绝致 龙卷风" },
        { "tornado5", "绝致 龙卷风改装版" },
        { "tornado6", "绝致 龙卷风破烂老爷车" },
        { "turismo2", "古罗帝 远途经典版" },
        { "viseris", "兰帕达缇 维瑟瑞斯" },
        { "z190", "卡林 190z" },
        { "zion3", "绝品 天堂经典版" },
        { "ztype", "特卢菲 Z 型" },
    };

    /// <summary>
    /// 6 当前分类: 跑车
    /// </summary>
    public static readonly Dictionary<string, string> Sports = new()
    {
        { "alpha", "亚班尼 阿尔法" },
        { "banshee", "冒险家 女妖" },
        { "bestiagts", "古罗帝 野兽 GTS" },
        { "blista2", "丁卡 小型旅行家" },
        { "blista3", "丁卡 冲冲猴旅行家" },
        { "buffalo", "冒险家 猛牛" },
        { "buffalo2", "冒险家 猛牛 S" },
        { "buffalo3", "冒险家 霜碧猛牛" },
        { "calico", "卡林 卡利科 GTF" },
        { "carbonizzare", "古罗帝 汗血宝马" },
        { "comet2", "菲斯特 陆上彗星" },
        { "comet3", "菲斯特 陆上彗星怀旧改装版" },
        { "comet4", "菲斯特 彗星狩猎者" },
        { "comet5", "菲斯特 陆上彗星 SR" },
        { "comet6", "菲斯特 陆上彗星 S2" },
        { "comet7", "菲斯特 陆上彗星 S2 敞篷版" },
        { "coquette", "非凡 艳妇" },
        { "coquette4", "非凡 艳妇 D10" },
        { "corsita", "兰帕达缇 科西塔" },
        { "cypher", "绝品 塞弗" },
        { "drafter", "奥北 8F 尾随者" },
        { "elegy", "爱尼仕 挽歌怀旧改装版" },
        { "elegy2", "爱尼仕 挽歌 RH8" },
        { "euros", "爱尼仕 欧洲" },
        { "everon2", "卡林 燃轨埃弗伦" },
        { "feltzer2", "贝飞特 飞特者" },
        { "flashgt", "威皮 闪电 GT" },
        { "furoregt", "兰帕达缇 沸洛雷 GT" },
        { "fusilade", "赛乐斯特 眩光" },
        { "futo", "卡林 福多" },
        { "futo2", "卡林 福多 GTX" },
        { "gb200", "威皮 GB200" },
        { "growler", "菲斯特 嚎叫者" },
        { "hotring", "绝致 燃轨军刀" },
        { "imorgon", "傲弗拉 明日" },
        { "issi7", "威尼 天威跑车版" },
        { "italigto", "古罗帝 义塔力 GTO" },
        { "italirsx", "古罗帝 义塔力 RSX" },
        { "jester", "丁卡 弄臣" },
        { "jester2", "丁卡 弄臣（赛车）" },
        { "jester3", "丁卡 弄臣经典版" },
        { "jester4", "丁卡 弄臣 RR" },
        { "jugular", "欧斯洛 扼喉" },
        { "khamelion", "海岬 变色龙" },
        { "komoda", "兰帕达缇 科莫达" },
        { "kuruma", "卡林 骷髅马" },
        { "kuruma2", "卡林 骷髅马（装甲版）" },
        { "locust", "欧斯洛 蝗虫" },
        { "lynx", "欧斯洛 山猫" },
        { "massacro", "浪子 马萨克罗" },
        { "massacro2", "浪子 马萨克罗（赛车）" },
        { "neo", "维沙 尼欧" },
        { "neon", "菲斯特 霓虹" },
        { "ninef", "奥北 9F" },
        { "ninef2", "奥北 9F 敞篷版" },
        { "omnis", "奥北 奥姆尼斯" },
        { "omnisegt", "奥北 奥姆尼斯 e-GT" },
        { "panthere", "苔原 潘瑟力" },
        { "paragon", "埃努斯 帕拉贡 R" },
        { "paragon2", "埃努斯 帕拉贡 R（装甲版）" },
        { "pariah", "欧斯洛 放逐者" },
        { "penumbra", "麦霸子 半影使者" },
        { "penumbra2", "麦霸子 半影使者 FF" },
        { "r300", "爱尼仕 300R" },
        { "raiden", "旋风 雷电" },
        { "rapidgt", "浪子 疾速 GT" },
        { "rapidgt2", "浪子 疾速 GT" },
        { "raptor", "毕福 迅猛龙" },
        { "remus", "爱尼仕 雷姆斯" },
        { "revolter", "绝品 反叛者" },
        { "rt3000", "丁卡 RT3000" },
        { "ruston", "海岬 拉斯顿" },
        { "schafter3", "贝飞特 莎夫特 V12" },
        { "schafter4", "贝飞特 长轴莎夫特" },
        { "schlagen", "贝飞特 撞击 GT" },
        { "schwarzer", "贝飞特 施瓦兹" },
        { "sentinel3", "绝品 卫士经典版" },
        { "sentinel4", "绝品 卫士经典宽体版" },
        { "seven70", "浪子 柒-70" },
        { "sm722", "贝飞特 SM722" },
        { "specter", "浪子 幽鬼" },
        { "specter2", "浪子 幽鬼改装版" },
        { "streiter", "贝飞特 斯垂特" },
        { "sugoi", "丁卡 斯国一" },
        { "sultan", "卡林 王者" },
        { "sultan2", "卡林 王者经典版" },
        { "sultan3", "卡林 王者 RS 经典版" },
        { "surano", "贝飞特 速雷" },
        { "tampa2", "绝致 漂移坦帕" },
        { "tenf", "奥北 10F" },
        { "tenf2", "奥北 10F 宽体版" },
        { "tropos", "兰帕达缇 逐波雷厉" },
        { "vectre", "皇霸天 韦柯特" },
        { "verlierer2", "冒险家 迷失者" },
        { "veto", "丁卡 微托经典版" },
        { "veto2", "丁卡 微托现代版" },
        { "vstr", "亚班尼 V-STR" },
        { "zr350", "爱尼仕 ZR350" },
        { "zr380", "爱尼仕 末日 ZR380" },
        { "zr3802", "爱尼仕 科幻 ZR380" },
        { "zr3803", "爱尼仕 梦魇 ZR380" },
    };

    /// <summary>
    /// 7 当前分类: 超级跑车
    /// </summary>
    public static readonly Dictionary<string, string> Super = new()
    {
        { "adder", "特卢菲 灵蛇" },
        { "autarch", "傲弗拉 独裁者" },
        { "banshee2", "冒险家 女妖 900R" },
        { "bullet", "威皮 子弹" },
        { "champion", "浪子 冠军" },
        { "cheetah", "古罗帝 猎豹" },
        { "cyclone", "旋风 飓风" },
        { "deveste", "普林西比 蹂躏者 8" },
        { "emerus", "培罗 艾梅鲁斯" },
        { "entity2", "傲弗拉 本质 XXR" },
        { "entity3", "傲弗拉 本质 MT" },
        { "entityxf", "傲弗拉 本质 XF" },
        { "fmj", "威皮 FMJ" },
        { "furia", "古罗帝 狂热" },
        { "gp1", "培罗 GP1" },
        { "ignus", "佩嘉西 伊格纳斯" },
        { "infernus", "佩嘉西 炼狱魔" },
        { "italigtb", "培罗 义塔力 GTB" },
        { "italigtb2", "培罗 义塔力 GTB 改装版" },
        { "krieger", "贝飞特 武夫" },
        { "le7b", "爱尼仕 RE-7B" },
        { "lm87", "贝飞特 LM87" },
        { "nero", "特卢菲 尼罗" },
        { "nero2", "特卢菲 尼罗改装版" },
        { "osiris", "佩嘉西 奥西里斯" },
        { "penetrator", "欧斯洛 穿刺者" },
        { "pfister811", "菲斯特 811" },
        { "prototipo", "古罗帝 X80 原型" },
        { "reaper", "佩嘉西 死神" },
        { "s80", "爱尼仕 S80RR" },
        { "sc1", "绝品 SC1" },
        { "scramjet", "绝致 超燃" },
        { "sheava", "皇霸天 ETR1" },
        { "sultanrs", "卡林 王者 RS" },
        { "t20", "培罗 T20" },
        { "taipan", "雪佛 泰斑" },
        { "tempesta", "佩嘉西 风暴" },
        { "tezeract", "佩嘉西 泰泽拉克" },
        { "thrax", "特卢菲 特拉克斯" },
        { "tigon", "兰帕达缇 虎狮兽" },
        { "torero2", "佩嘉西 斗牛 XO" },
        { "turismor", "古罗帝 远途 R" },
        { "tyrant", "傲弗拉 统治者" },
        { "tyrus", "培罗 泰勒斯" },
        { "vacca", "佩嘉西 狂牛" },
        { "vagner", "浪子 瓦格纳" },
        { "vigilante", "义警" },
        { "virtue", "欧斯洛 美德" },
        { "visione", "古罗帝 幻象" },
        { "voltic", "旋风 狂雷" },
        { "voltic2", "旋风 火箭狂雷" },
        { "xa21", "欧斯洛 XA-21" },
        { "zeno", "傲弗拉 捷诺" },
        { "zentorno", "佩嘉西 桑托劳" },
        { "zorrusso", "佩嘉西 佐路索" },
    };

    /// <summary>
    /// 8 当前分类: 摩托车
    /// </summary>
    public static readonly Dictionary<string, string> Motorcycles = new()
    {
        { "akuma", "丁卡 街头恶魔" },
        { "avarus", "LCC 阿瓦鲁斯" },
        { "bagger", "西部 驮兽" },
        { "bati", "佩嘉西 801 巴提" },
        { "bati2", "佩嘉西 801RR 巴提" },
        { "bf400", "长崎 BF400" },
        { "carbonrs", "长崎 碳纤 RS 型" },
        { "chimera", "长崎 奇美拉" },
        { "cliffhanger", "西部 高潮" },
        { "daemon", "西部 恶魔" },
        { "daemon2", "西部 恶魔" },
        { "deathbike", "西部 末日丧尸" },
        { "deathbike2", "西部 科幻丧尸" },
        { "deathbike3", "西部 梦魇丧尸" },
        { "defiler", "诗津 亵渎者" },
        { "diablous", "普林西比 蒂雅布萝" },
        { "diablous2", "普林西比 蒂雅布萝改装版" },
        { "double", "丁卡 双 T" },
        { "enduro", "丁卡 恩斗罗" },
        { "esskey", "佩嘉西 爱时吉" },
        { "faggio", "佩嘉西 费甲欧现代版" },
        { "faggio2", "佩嘉西 费甲欧" },
        { "faggio3", "佩嘉西 费甲欧摩登版" },
        { "fcr", "佩嘉西 FCR 1000" },
        { "fcr2", "佩嘉西 FCR 1000 改装版" },
        { "gargoyle", "西部 石像鬼" },
        { "hakuchou", "诗津 白鸟" },
        { "hakuchou2", "诗津 白鸟竞速版" },
        { "hexer", "LCC 迷魅光轮" },
        { "innovation", "LCC 创新" },
        { "lectro", "普林西比 雷克卓" },
        { "manchez", "麦霸子 曼切兹" },
        { "manchez2", "麦霸子 曼切兹侦查" },
        { "manchez3", "麦霸子 曼切兹侦查 C" },
        { "nemesis", "普林西比 复仇女神" },
        { "nightblade", "西部 夜刃" },
        { "oppressor", "佩嘉西 暴君" },
        { "oppressor2", "佩嘉西 暴君 Mk 2" },
        { "pcj", "诗津 PCJ 600" },
        { "powersurge", "西部 电涌" },
        { "ratbike", "西部 破烂摩托车" },
        { "reever", "西部 里弗" },
        { "rrocket", "西部 狂暴火箭" },
        { "ruffian", "佩嘉西 恶霸" },
        { "sanchez", "麦霸子 桑切斯（涂装版）" },
        { "sanchez2", "麦霸子 桑切斯" },
        { "sanctus", "LCC 圣驹" },
        { "shinobi", "长崎 信奴比" },
        { "shotaro", "长崎 圣太郎" },
        { "sovereign", "西部 君主" },
        { "stryder", "长崎 斯特德" },
        { "thrust", "丁卡 猛冲" },
        { "vader", "诗津 威德" },
        { "vindicator", "丁卡 审判者" },
        { "vortex", "佩嘉西 漩涡" },
        { "wolfsbane", "西部 恶狼克星" },
        { "zombiea", "西部 鞭尸者" },
        { "zombieb", "西部 碎尸者" },
    };

    /// <summary>
    /// 9 当前分类: 越野车
    /// </summary>
    public static readonly Dictionary<string, string> OffRoad = new()
    {
        { "bfinjection", "毕福 沙丘征服者" },
        { "bifta", "毕福 必浮塔" },
        { "blazer", "长崎 烈焰" },
        { "blazer2", "长崎 烈焰救生型" },
        { "blazer3", "长崎 火辣烈焰" },
        { "blazer4", "长崎 街头烈焰" },
        { "blazer5", "长崎 水陆烈焰骑士" },
        { "bodhi2", "卡尼斯 万用行者" },
        { "boor", "卡林 粗人" },
        { "brawler", "旋风 斗殴者" },
        { "bruiser", "贝飞特 末日捍士" },
        { "bruiser2", "贝飞特 科幻捍士" },
        { "bruiser3", "贝飞特 梦魇捍士" },
        { "brutus", "绝致 末日布鲁图斯" },
        { "brutus2", "绝致 科幻布鲁图斯" },
        { "brutus3", "绝致 梦魇布鲁图斯" },
        { "caracara", "威皮 卡拉卡拉" },
        { "caracara2", "威皮 卡拉卡拉四驱车" },
        { "dloader", "冒险家 越野游侠" },
        { "draugur", "绝致 德劳古尔" },
        { "dubsta3", "贝飞特 迪布达 6x6" },
        { "dune", "毕福 沙丘魔宝" },
        { "dune2", "太空码头工" },
        { "dune3", "毕福 沙丘 FAV" },
        { "dune4", "斜面魔宝" },
        { "dune5", "斜面魔宝" },
        { "everon", "卡林 埃弗伦" },
        { "freecrawler", "卡尼斯 自由攀登者" },
        { "hellion", "爱尼仕 恶人" },
        { "insurgent", "HVY 叛乱分子皮卡" },
        { "insurgent2", "HVY 叛乱分子" },
        { "insurgent3", "HVY 叛乱分子皮卡改装版" },
        { "kalahari", "卡尼斯 卡拉哈里" },
        { "kamacho", "卡尼斯 卡马乔" },
        { "marshall", "雪佛 马绍尔" },
        { "menacer", "HVY 威胁者" },
        { "mesa3", "卡尼斯 炎魔" },
        { "monster", "威皮 解放者" },
        { "monster3", "冒险家 末日大脚怪" },
        { "monster4", "冒险家 科幻大脚怪" },
        { "monster5", "冒险家 梦魇大脚怪" },
        { "nightshark", "HVY 夜鲨" },
        { "outlaw", "长崎 不法之徒" },
        { "patriot3", "巨象 爱国者军用版" },
        { "rancherxl", "绝致 蓝彻 XL" },
        { "rancherxl2", "绝致 蓝彻 XL" },
        { "rcbandito", "RC 匪徒" },
        { "rebel", "卡林 叛逆男女生锈版" },
        { "rebel2", "卡林 叛逆男女" },
        { "riata", "威皮 利雅塔" },
        { "sandking", "威皮 大脚霸王 XL" },
        { "sandking2", "威皮 大脚霸王 SWB" },
        { "technical", "卡林 铁尼高" },
        { "technical2", "卡林 水陆铁尼高" },
        { "technical3", "卡林 铁尼高改装版" },
        { "trophytruck", "威皮 越野卡车" },
        { "trophytruck2", "威皮 沙漠突击" },
        { "vagrant", "麦克斯韦 流浪者" },
        { "verus", "丁卡 维鲁斯" },
        { "winky", "威皮 威起" },
        { "yosemite3", "绝致 约塞米蒂蓝彻" },
        { "zhaba", "卢恩 炸吧" },
    };

    /// <summary>
    /// 10 当前分类: 工业用车
    /// </summary>
    public static readonly Dictionary<string, string> Industrial = new()
    {
        { "bulldozer", "HVY 推土机" },
        { "cutter", "HVY 钻洞机" },
        { "dump", "HVY 矿石搬运车" },
        { "flatbed", "MTL 平板拖车" },
        { "guardian", "威皮 守护者" },
        { "handler", "码头装卸车" },
        { "mixer", "HVY 混凝土搅拌车" },
        { "mixer2", "HVY 混凝土搅拌车" },
        { "rubble", "乔氏 砂通天" },
        { "tiptruck", "威霸 工地倾卸车" },
        { "tiptruck2", "工地倾卸车" },
    };

    /// <summary>
    /// 11 当前分类: 公共事业用车
    /// </summary>
    public static readonly Dictionary<string, string> Utility = new()
    {
        { "airtug", "行李拖车" },
        { "armytanker", "军用拖车" },
        { "armytrailer", "军用拖车" },
        { "armytrailer2", "军用拖车" },
        { "baletrailer", "草捆拖车" },
        { "boattrailer", "拖船" },
        { "caddy", "高尔夫球车" },
        { "caddy2", "高尔夫球车" },
        { "caddy3", "高尔夫球车" },
        { "docktrailer", "" },
        { "docktug", "码头拖车" },
        { "forklift", "HVY 叉车" },
        { "freighttrailer", "" },
        { "graintrailer", "" },
        { "mower", "割草车" },
        { "proptrailer", "" },
        { "raketrailer", "拖车" },
        { "ripley", "机场牵引车" },
        { "sadler", "威皮 沙德勒" },
        { "sadler2", "威皮 沙德勒" },
        { "scrap", "废五金回收车" },
        { "slamtruck", "威皮 大满贯卡车" },
        { "tanker", "拖车" },
        { "tanker2", "" },
        { "towtruck", "拖吊车" },
        { "towtruck2", "拖吊车" },
        { "tr2", "拖车" },
        { "tr3", "拖车" },
        { "tr4", "拖车" },
        { "tractor", "老式拖拉机" },
        { "tractor2", "斯坦利 农耕机" },
        { "tractor3", "斯坦利 农耕机" },
        { "trailerlarge", "机动作战中心" },
        { "trailerlogs", "拖车" },
        { "trailers", "拖车" },
        { "trailers2", "拖车" },
        { "trailers3", "拖车" },
        { "trailers4", "拖车" },
        { "trailersmall", "拖车" },
        { "trflat", "拖车" },
        { "tvtrailer", "拖车" },
        { "utillitruck", "公共事业卡车" },
        { "utillitruck2", "公共事业卡车" },
        { "utillitruck3", "公共事业卡车" },
    };

    /// <summary>
    /// 12 当前分类: 厢型车
    /// </summary>
    public static readonly Dictionary<string, string> Vans = new()
    {
        { "bison", "冒险家 野牛" },
        { "bison2", "冒险家 野牛" },
        { "bison3", "冒险家 野牛" },
        { "bobcatxl", "威皮 雄猫 XL" },
        { "boxville", "威霸 厢村" },
        { "boxville2", "厢村" },
        { "boxville3", "威霸 厢村" },
        { "boxville4", "威霸 厢村" },
        { "boxville5", "装甲版厢村" },
        { "burrito", "绝致 屌客" },
        { "burrito2", "绝致 除虫大师屌客" },
        { "burrito3", "绝致 屌客" },
        { "burrito4", "绝致 屌客" },
        { "burrito5", "绝致 屌客" },
        { "camper", "威霸 露营车" },
        { "gburrito", "绝致 屌客帮派版" },
        { "gburrito2", "绝致 屌客帮派版" },
        { "journey", "赛柯尼 安旅者" },
        { "journey2", "赛柯尼 安旅者 2" },
        { "minivan", "威皮 迷你厢型车" },
        { "minivan2", "威皮 迷你厢型车改装版" },
        { "paradise", "冒险家 天堂" },
        { "pony", "威霸 小马" },
        { "pony2", "威霸 小马" },
        { "rumpo", "冒险家 澜波" },
        { "rumpo2", "冒险家 澜波" },
        { "rumpo3", "冒险家 澜波改装版" },
        { "speedo", "威皮 劲速" },
        { "speedo2", "威皮 小丑花车" },
        { "speedo4", "威皮 劲速改装版" },
        { "surfer", "毕福 乘风" },
        { "surfer2", "毕福 乘风" },
        { "surfer3", "毕福 乘风改装版" },
        { "taco", "玉米饼餐车" },
        { "youga", "冒险家 游侠" },
        { "youga2", "冒险家 游侠经典版" },
        { "youga3", "冒险家 游侠经典四驱车" },
        { "youga4", "威皮 游侠改装版" },
    };

    /// <summary>
    /// 13 当前分类: 自行车
    /// </summary>
    public static readonly Dictionary<string, string> Cycles = new()
    {
        { "bmx", "BMX" },
        { "cruiser", "巡航者" },
        { "fixter", "费斯特" },
        { "scorcher", "先驱者" },
        { "tribike", "惠比特竞速自行车" },
        { "tribike2", "极限耐力竞速自行车" },
        { "tribike3", "特莱赛可竞速自行车" },
    };

    /// <summary>
    /// 14 当前分类: 船
    /// </summary>
    public static readonly Dictionary<string, string> Boats = new()
    {
        { "avisa", "海怪 阿维萨" },
        { "dinghy", "长崎 小艇" },
        { "dinghy2", "长崎 小艇" },
        { "dinghy3", "长崎 小艇" },
        { "dinghy4", "长崎 小艇" },
        { "dinghy5", "长崎 武装小艇" },
        { "jetmax", "诗津 极限快艇" },
        { "kosatka", "卢恩 虎鲸" },
        { "longfin", "诗津 长鳍" },
        { "marquis", "丁卡 水上侯爵" },
        { "patrolboat", "库尔兹 31 巡逻艇" },
        { "predator", "警用追猎快艇" },
        { "seashark", "水上枭雄 海鲨摩托艇" },
        { "seashark2", "水上枭雄 海鲨摩托艇" },
        { "seashark3", "水上枭雄 海鲨摩托艇" },
        { "speeder", "佩嘉西 飙速" },
        { "speeder2", "佩嘉西 飙速" },
        { "squalo", "诗津 思快乐快艇" },
        { "submersible", "潜水艇" },
        { "submersible2", "海怪" },
        { "suntrap", "诗津 向阳号" },
        { "toro", "兰帕达缇 公牛" },
        { "toro2", "兰帕达缇 公牛" },
        { "tropic", "诗津 烈阳号" },
        { "tropic2", "诗津 烈阳号" },
        { "tug", "拖船" },
    };

    /// <summary>
    /// 15 当前分类: 直升机
    /// </summary>
    public static readonly Dictionary<string, string> Helicopters = new()
    {
        { "akula", "阿库拉" },
        { "annihilator", "歼灭者" },
        { "annihilator2", "歼灭者隐形版" },
        { "buzzard", "秃鹰攻击直升机" },
        { "buzzard2", "秃鹰直升机" },
        { "cargobob", "运兵直升机" },
        { "cargobob2", "运兵直升机" },
        { "cargobob3", "运兵直升机" },
        { "cargobob4", "运兵直升机" },
        { "conada", "白金汉 康纳达" },
        { "frogger", "穿梭者" },
        { "frogger2", "穿梭者" },
        { "havok", "长崎 浩劫者" },
        { "hunter", "FH-1 猎杀者" },
        { "maverick", "小蛮牛" },
        { "polmav", "警用小蛮牛" },
        { "savage", "野蛮人" },
        { "seasparrow", "海雀" },
        { "seasparrow2", "麻雀" },
        { "seasparrow3", "麻雀" },
        { "skylift", "吊挂直升机" },
        { "supervolito", "白金汉 超级沃利托" },
        { "supervolito2", "白金汉 超级沃利托碳纤版" },
        { "swift", "白金汉 斯威夫特" },
        { "swift2", "白金汉 斯威夫特豪华版" },
        { "valkyrie", "女武神" },
        { "valkyrie2", "女武神 MOD.0" },
        { "volatus", "白金汉 弗拉图斯" },
    };

    /// <summary>
    /// 16 当前分类: 飞机
    /// </summary>
    public static readonly Dictionary<string, string> Planes = new()
    {
        { "alkonost", "RO-86 阿尔科诺斯特" },
        { "alphaz1", "白金汉 阿尔法-Z1" },
        { "avenger", "巨象 复仇者" },
        { "avenger2", "巨象 复仇者" },
        { "besra", "西部 雀鹰" },
        { "blimp", "原子飞艇" },
        { "blimp2", "希罗飞艇" },
        { "blimp3", "飞艇" },
        { "bombushka", "RM-10 邦布什卡" },
        { "cargoplane", "货机" },
        { "cargoplane2", "货机" },
        { "cuban800", "古邦 800" },
        { "dodo", "巨象 嘟嘟鸟" },
        { "duster", "洒药机" },
        { "howard", "白金汉 霍华德 NX-25" },
        { "hydra", "巨象 九头蛇" },
        { "jet", "喷气机" },
        { "lazer", "P-996 天煞" },
        { "luxor", "白金汉 乐梭" },
        { "luxor2", "白金汉 乐梭豪华版" },
        { "mammatus", "天行巨兽" },
        { "microlight", "长崎 鸿毛" },
        { "miljet", "白金汉 军用喷气机" },
        { "mogul", "巨象 莫古尔" },
        { "molotok", "V-65 莫洛托克" },
        { "nimbus", "白金汉 灵气号" },
        { "nokota", "P-45 诺克塔" },
        { "pyro", "白金汉 狂焰" },
        { "rogue", "西部 恶徒" },
        { "seabreeze", "西部 海风" },
        { "shamal", "白金汉 夏玛尔客机" },
        { "starling", "LF-22 星椋" },
        { "strikeforce", "B-11 突击部队" },
        { "stunt", "野鸭" },
        { "titan", "泰坦号" },
        { "tula", "巨象 图拉" },
        { "velum", "梅杜莎" },
        { "velum2", "梅杜莎 5 座" },
        { "vestra", "白金汉 威斯特拉" },
        { "volatol", "沃拉托" },
    };

    /// <summary>
    /// 17 当前分类: 服务用车
    /// </summary>
    public static readonly Dictionary<string, string> Service = new()
    {
        { "airbus", "机场巴士" },
        { "brickade", "MTL 布里凯德" },
        { "brickade2", "MTL 布里凯德 6x6" },
        { "bus", "巴士" },
        { "coach", "白狗巴士" },
        { "pbus2", "音乐节巴士" },
        { "rallytruck", "MTL 沙丘" },
        { "rentalbus", "租用穿梭巴士" },
        { "taxi", "出租车" },
        { "tourbus", "观光巴士" },
        { "trash", "垃圾大王" },
        { "trash2", "垃圾大王" },
        { "wastelander", "MTL 拓荒者" },
    };

    /// <summary>
    /// 18 当前分类: 特种车
    /// </summary>
    public static readonly Dictionary<string, string> Emergency = new()
    {
        { "ambulance", "救护车" },
        { "fbi", "FIB" },
        { "fbi2", "FIB" },
        { "firetruk", "MTL 消防车" },
        { "lguard", "绝致 沙滩急救车" },
        { "pbus", "移监巴士" },
        { "police", "警用巡逻车" },
        { "police2", "警用巡逻车" },
        { "police3", "警用巡逻车" },
        { "police4", "无标识巡航者" },
        { "policeb", "警用摩托车" },
        { "policeold1", "警用蓝彻" },
        { "policeold2", "警用公路巡逻车" },
        { "policet", "警用运输车" },
        { "pranger", "国家公园警用车" },
        { "riot", "警用防暴车" },
        { "riot2", "防暴车" },
        { "sheriff", "警长座车" },
        { "sheriff2", "警长 SUV" },
    };

    /// <summary>
    /// 19 当前分类: 军用车
    /// </summary>
    public static readonly Dictionary<string, string> Military = new()
    {
        { "apc", "HVY APC" },
        { "barracks", "地霸王" },
        { "barracks2", "HVY 拖车型地霸王" },
        { "barracks3", "地霸王" },
        { "barrage", "巴拉杰" },
        { "chernobog", "切尔诺伯格" },
        { "crusader", "卡尼斯 傲世铁骑" },
        { "halftrack", "冒险家 半履战车" },
        { "khanjali", "TM-02 可汗贾利" },
        { "minitank", "入侵与说服 坦克" },
        { "rhino", "犀牛坦克" },
        { "scarab", "HVY 末日圣甲虫" },
        { "scarab2", "HVY 科幻圣甲虫" },
        { "scarab3", "HVY 梦魇圣甲虫" },
        { "thruster", "巨象 推进者" },
        { "trailersmall2", "冯·伏厄 防空拖车" },
        { "vetir", "维泰尔" },
    };

    /// <summary>
    /// 20 当前分类: 商用车
    /// </summary>
    public static readonly Dictionary<string, string> Commercial = new()
    {
        { "benson", "威皮 班森" },
        { "biff", "HVY 倾卸车" },
        { "cerberus", "MTL 末日地狱犬" },
        { "cerberus2", "MTL 科幻地狱犬" },
        { "cerberus3", "MTL 梦魇地狱犬" },
        { "hauler", "乔氏 搬运者" },
        { "hauler2", "乔氏 搬运者改装版" },
        { "mule", "麦霸子 猛骡" },
        { "mule2", "麦霸子 猛骡" },
        { "mule3", "麦霸子 猛骡" },
        { "mule4", "麦霸子 猛骡改装版" },
        { "mule5", "麦霸子 猛骡" },
        { "packer", "MTL 车辆运送车" },
        { "phantom", "乔氏 魅影" },
        { "phantom2", "乔氏 尖锥魅影" },
        { "phantom3", "乔氏 魅影改装版" },
        { "pounder", "MTL 跑德" },
        { "pounder2", "MTL 跑德改装版" },
        { "stockade", "威霸 拦截者" },
        { "stockade3", "威霸 拦截者" },
        { "terbyte", "贝飞特 恐霸" },
    };

    /// <summary>
    /// 21 当前分类: 火车
    /// </summary>
    public static readonly Dictionary<string, string> Trains = new()
    {
        { "cablecar", "缆车" },
        { "freight", "货运列车" },
        { "freightcar", "货运列车" },
        { "freightcar2", "货运列车" },
        { "freightcont1", "货运列车" },
        { "freightcont2", "货运列车" },
        { "freightgrain", "货运列车" },
        { "metrotrain", "货运列车" },
        { "tankercar", "货运列车" },
    };

    /// <summary>
    /// 22 当前分类: 开轮式
    /// </summary>
    public static readonly Dictionary<string, string> OpenWheel = new()
    {
        { "formula", "培罗 PR4" },
        { "formula2", "欧斯洛 R88" },
        { "openwheel1", "贝飞特 BR8" },
        { "openwheel2", "绝致 DR1" },
    };

    /// <summary>
    /// 载具分类
    /// </summary>
    public static readonly Dictionary<string, Dictionary<string, string>> VehicleTypes = new()
    {
        /*
             0 当前分类: 小型汽车
             1 当前分类: 轿车
             2 当前分类: SUV
             3 当前分类: 轿跑车
             4 当前分类: 肌肉车
             5 当前分类: 经典跑车
             6 当前分类: 跑车
             7 当前分类: 超级跑车
             8 当前分类: 摩托车
             9 当前分类: 越野车
            10 当前分类: 工业用车
            11 当前分类: 公共事业用车
            12 当前分类: 厢型车
            13 当前分类: 自行车
            14 当前分类: 船
            15 当前分类: 直升机
            16 当前分类: 飞机
            17 当前分类: 服务用车
            18 当前分类: 特种车
            19 当前分类: 军用车
            20 当前分类: 商用车
            21 当前分类: 火车
            22 当前分类: 开轮式
         */
        { "小型汽车", Compacts },
        { "轿车", Sedans },
        { "SUV", SUVs },
        { "轿跑车", Coupes },
        { "肌肉车", Muscle },
        { "经典跑车", SportsClassics },
        { "跑车", Sports },
        { "超级跑车", Super },
        { "摩托车", Motorcycles },
        { "越野车", OffRoad },
        { "工业用车", Industrial },
        { "公共事业用车", Utility },
        { "厢型车", Vans },
        { "自行车", Cycles },
        { "船", Boats },
        { "直升机", Helicopters },
        { "飞机", Planes },
        { "服务用车", Service },
        { "特种车", Emergency },
        { "军用车", Military },
        { "商用车", Commercial },
        { "火车", Trains },
        { "开轮式", OpenWheel },
    };
}
