namespace GTA5Core.RAGE.Vehicles;

public static class VehicleColor
{
    public class ColorInfo
    {
        public string Name { get; set; }
        public int Value { get; set; }
    }

    /// <summary>
    /// 载具颜色
    /// </summary>
    public static readonly List<ColorInfo> Colors = new()
    {
        new ColorInfo(){ Name="随机", Value=-1 },
        new ColorInfo(){ Name="Metallic Black", Value=0 },
        new ColorInfo(){ Name="Metallic Graphite Black", Value=1 },
        new ColorInfo(){ Name="Metallic Black Steal", Value=2 },
        new ColorInfo(){ Name="Metallic Dark Silver", Value=3 },
        new ColorInfo(){ Name="Metallic Silver", Value=4 },
        new ColorInfo(){ Name="Metallic Blue Silver", Value=5 },
        new ColorInfo(){ Name="Metallic Steel Gray", Value=6 },
        new ColorInfo(){ Name="Metallic Shadow Silver", Value=7 },
        new ColorInfo(){ Name="Metallic Stone Silver", Value=8 },
        new ColorInfo(){ Name="Metallic Midnight Silver", Value=9 },
        new ColorInfo(){ Name="Metallic Gun Metal", Value=10 },
        new ColorInfo(){ Name="Metallic Anthracite Grey", Value=11 },
        new ColorInfo(){ Name="Matte Black", Value=12 },
        new ColorInfo(){ Name="Matte Gray", Value=13 },
        new ColorInfo(){ Name="Matte Light Grey", Value=14 },
        new ColorInfo(){ Name="Util Black", Value=15 },
        new ColorInfo(){ Name="Util Black Poly", Value=16 },
        new ColorInfo(){ Name="Util Dark silver", Value=17 },
        new ColorInfo(){ Name="Util Silver", Value=18 },
        new ColorInfo(){ Name="Util Gun Metal", Value=19 },
        new ColorInfo(){ Name="Util Shadow Silver", Value=20 },
        new ColorInfo(){ Name="Worn Black", Value=21 },
        new ColorInfo(){ Name="Worn Graphite", Value=22 },
        new ColorInfo(){ Name="Worn Silver Grey", Value=23 },
        new ColorInfo(){ Name="Worn Silver", Value=24 },
        new ColorInfo(){ Name="Worn Blue Silver", Value=25 },
        new ColorInfo(){ Name="Worn Shadow Silver", Value=26 },
        new ColorInfo(){ Name="Metallic Red", Value=27 },
        new ColorInfo(){ Name="Metallic Torino Red", Value=28 },
        new ColorInfo(){ Name="Metallic Formula Red", Value=29 },
        new ColorInfo(){ Name="Metallic Blaze Red", Value=30 },
        new ColorInfo(){ Name="Metallic Graceful Red", Value=31 },
        new ColorInfo(){ Name="Metallic Garnet Red", Value=32 },
        new ColorInfo(){ Name="Metallic Desert Red", Value=33 },
        new ColorInfo(){ Name="Metallic Cabernet Red", Value=34 },
        new ColorInfo(){ Name="Metallic Candy Red", Value=35 },
        new ColorInfo(){ Name="Metallic Sunrise Orange", Value=36 },
        new ColorInfo(){ Name="Metallic Classic Gold", Value=37 },
        new ColorInfo(){ Name="Metallic Orange", Value=38 },
        new ColorInfo(){ Name="Matte Red", Value=39 },
        new ColorInfo(){ Name="Matte Dark Red", Value=40 },
        new ColorInfo(){ Name="Matte Orange", Value=41 },
        new ColorInfo(){ Name="Matte Yellow", Value=42 },
        new ColorInfo(){ Name="Util Red", Value=43 },
        new ColorInfo(){ Name="Util Bright Red", Value=44 },
        new ColorInfo(){ Name="Util Garnet Red", Value=45 },
        new ColorInfo(){ Name="Worn Red", Value=46 },
        new ColorInfo(){ Name="Worn Golden Red", Value=47 },
        new ColorInfo(){ Name="Worn Dark Red", Value=48 },
        new ColorInfo(){ Name="Metallic Dark Green", Value=49 },
        new ColorInfo(){ Name="Metallic Racing Green", Value=50 },
        new ColorInfo(){ Name="Metallic Sea Green", Value=51 },
        new ColorInfo(){ Name="Metallic Olive Green", Value=52 },
        new ColorInfo(){ Name="Metallic Green", Value=53 },
        new ColorInfo(){ Name="Metallic Gasoline Blue Green", Value=54 },
        new ColorInfo(){ Name="Matte Lime Green", Value=55 },
        new ColorInfo(){ Name="Util Dark Green", Value=56 },
        new ColorInfo(){ Name="Util Green", Value=57 },
        new ColorInfo(){ Name="Worn Dark Green", Value=58 },
        new ColorInfo(){ Name="Worn Green", Value=59 },
        new ColorInfo(){ Name="Worn Sea Wash", Value=60 },
        new ColorInfo(){ Name="Metallic Midnight Blue", Value=61 },
        new ColorInfo(){ Name="Metallic Dark Blue", Value=62 },
        new ColorInfo(){ Name="Metallic Saxony Blue", Value=63 },
        new ColorInfo(){ Name="Metallic Blue", Value=64 },
        new ColorInfo(){ Name="Metallic Mariner Blue", Value=65 },
        new ColorInfo(){ Name="Metallic Harbor Blue", Value=66 },
        new ColorInfo(){ Name="Metallic Diamond Blue", Value=67 },
        new ColorInfo(){ Name="Metallic Surf Blue", Value=68 },
        new ColorInfo(){ Name="Metallic Nautical Blue", Value=69 },
        new ColorInfo(){ Name="Metallic Bright Blue", Value=70 },
        new ColorInfo(){ Name="Metallic Purple Blue", Value=71 },
        new ColorInfo(){ Name="Metallic Spinnaker Blue", Value=72 },
        new ColorInfo(){ Name="Metallic Ultra Blue", Value=73 },
        new ColorInfo(){ Name="Metallic Bright Blue", Value=74 },
        new ColorInfo(){ Name="Util Dark Blue", Value=75 },
        new ColorInfo(){ Name="Util Midnight Blue", Value=76 },
        new ColorInfo(){ Name="Util Blue", Value=77 },
        new ColorInfo(){ Name="Util Sea Foam Blue", Value=78 },
        new ColorInfo(){ Name="Uil Lightning blue", Value=79 },
        new ColorInfo(){ Name="Util Maui Blue Poly", Value=80 },
        new ColorInfo(){ Name="Util Bright Blue", Value=81 },
        new ColorInfo(){ Name="Matte Dark Blue", Value=82 },
        new ColorInfo(){ Name="Matte Blue", Value=83 },
        new ColorInfo(){ Name="Matte Midnight Blue", Value=84 },
        new ColorInfo(){ Name="Worn Dark blue", Value=85 },
        new ColorInfo(){ Name="Worn Blue", Value=86 },
        new ColorInfo(){ Name="Worn Light blue", Value=87 },
        new ColorInfo(){ Name="Metallic Taxi Yellow", Value=88 },
        new ColorInfo(){ Name="Metallic Race Yellow", Value=89 },
        new ColorInfo(){ Name="Metallic Bronze", Value=90 },
        new ColorInfo(){ Name="Metallic Yellow Bird", Value=91 },
        new ColorInfo(){ Name="Metallic Lime", Value=92 },
        new ColorInfo(){ Name="Metallic Champagne", Value=93 },
        new ColorInfo(){ Name="Metallic Pueblo Beige", Value=94 },
        new ColorInfo(){ Name="Metallic Dark Ivory", Value=95 },
        new ColorInfo(){ Name="Metallic Choco Brown", Value=96 },
        new ColorInfo(){ Name="Metallic Golden Brown", Value=97 },
        new ColorInfo(){ Name="Metallic Light Brown", Value=98 },
        new ColorInfo(){ Name="Metallic Straw Beige", Value=99 },
        new ColorInfo(){ Name="Metallic Moss Brown", Value=100 },
        new ColorInfo(){ Name="Metallic Biston Brown", Value=101 },
        new ColorInfo(){ Name="Metallic Beechwood", Value=102 },
        new ColorInfo(){ Name="Metallic Dark Beechwood", Value=103 },
        new ColorInfo(){ Name="Metallic Choco Orange", Value=104 },
        new ColorInfo(){ Name="Metallic Beach Sand", Value=105 },
        new ColorInfo(){ Name="Metallic Sun Bleeched Sand", Value=106 },
        new ColorInfo(){ Name="Metallic Cream", Value=107 },
        new ColorInfo(){ Name="Util Brown", Value=108 },
        new ColorInfo(){ Name="Util Medium Brown", Value=109 },
        new ColorInfo(){ Name="Util Light Brown", Value=110 },
        new ColorInfo(){ Name="Metallic White", Value=111 },
        new ColorInfo(){ Name="Metallic Frost White", Value=112 },
        new ColorInfo(){ Name="Worn Honey Beige", Value=113 },
        new ColorInfo(){ Name="Worn Brown", Value=114 },
        new ColorInfo(){ Name="Worn Dark Brown", Value=115 },
        new ColorInfo(){ Name="Worn straw beige", Value=116 },
        new ColorInfo(){ Name="Brushed Steel", Value=117 },
        new ColorInfo(){ Name="Brushed Black steel", Value=118 },
        new ColorInfo(){ Name="Brushed Aluminium", Value=119 },
        new ColorInfo(){ Name="Chrome", Value=120 },
        new ColorInfo(){ Name="Worn Off White", Value=121 },
        new ColorInfo(){ Name="Util Off White", Value=122 },
        new ColorInfo(){ Name="Worn Orange", Value=123 },
        new ColorInfo(){ Name="Worn Light Orange", Value=124 },
        new ColorInfo(){ Name="Metallic Securicor Green", Value=125 },
        new ColorInfo(){ Name="Worn Taxi Yellow", Value=126 },
        new ColorInfo(){ Name="police car blue", Value=127 },
        new ColorInfo(){ Name="Matte Green", Value=128 },
        new ColorInfo(){ Name="Matte Brown", Value=129 },
        new ColorInfo(){ Name="Worn Orange", Value=130 },
        new ColorInfo(){ Name="Matte White", Value=131 },
        new ColorInfo(){ Name="Worn White", Value=132 },
        new ColorInfo(){ Name="Worn Olive Army Green", Value=133 },
        new ColorInfo(){ Name="Pure White", Value=134 },
        new ColorInfo(){ Name="Hot Pink", Value=135 },
        new ColorInfo(){ Name="Salmon pink", Value=136 },
        new ColorInfo(){ Name="Metallic Vermillion Pink", Value=137 },
        new ColorInfo(){ Name="Orange", Value=138 },
        new ColorInfo(){ Name="Green", Value=139 },
        new ColorInfo(){ Name="Blue", Value=140 },
        new ColorInfo(){ Name="Mettalic Black Blue", Value=141 },
        new ColorInfo(){ Name="Metallic Black Purple", Value=142 },
        new ColorInfo(){ Name="Metallic Black Red", Value=143 },
        new ColorInfo(){ Name="hunter green", Value=144 },
        new ColorInfo(){ Name="Metallic Purple", Value=145 },
        new ColorInfo(){ Name="Metaillic V Dark Blue", Value=146 },
        new ColorInfo(){ Name="MODSHOP BLACK1", Value=147 },
        new ColorInfo(){ Name="Matte Purple", Value=148 },
        new ColorInfo(){ Name="Matte Dark Purple", Value=149 },
        new ColorInfo(){ Name="Metallic Lava Red", Value=150 },
        new ColorInfo(){ Name="Matte Forest Green", Value=151 },
        new ColorInfo(){ Name="Matte Olive Drab", Value=152 },
        new ColorInfo(){ Name="Matte Desert Brown", Value=153 },
        new ColorInfo(){ Name="Matte Desert Tan", Value=154 },
        new ColorInfo(){ Name="Matte Foilage Green", Value=155 },
        new ColorInfo(){ Name="DEFAULT ALLOY COLOR", Value=156 },
        new ColorInfo(){ Name="Epsilon Blue", Value=157 },
    };

    /// <summary>
    /// 载具灯光
    /// </summary>
    public static readonly List<ColorInfo> Lights = new()
    {
        new ColorInfo(){ Name="Blue", Value=3 },
        new ColorInfo(){ Name="Electric Blue", Value=4 },
        new ColorInfo(){ Name="Mint Green", Value=5 },
        new ColorInfo(){ Name="Lime Green", Value=6 },
        new ColorInfo(){ Name="Yellow", Value=7 },
        new ColorInfo(){ Name="Golden Shower", Value=8 },
        new ColorInfo(){ Name="Orange", Value=9 },
        new ColorInfo(){ Name="Red", Value=10 },
        new ColorInfo(){ Name="Pony Pink", Value=11 },
        new ColorInfo(){ Name="Hot Pink", Value=12 },
        new ColorInfo(){ Name="Purple", Value=13 },
        new ColorInfo(){ Name="Blacklight", Value=14 },
    };

    /// <summary>
    /// 班尼车轮
    /// </summary>
    public static readonly List<ColorInfo> Bennys = new()
    {
        new ColorInfo(){ Name="White Lines", Value=32 },
        new ColorInfo(){ Name="Classic WW", Value=63 },
        new ColorInfo(){ Name="Retro WW", Value=94 },
        new ColorInfo(){ Name="Red Lines", Value=125 },
        new ColorInfo(){ Name="Blue Lines", Value=156 },
        new ColorInfo(){ Name="Atomic", Value=187 },
    };

    /// <summary>
    /// 载具喇叭
    /// </summary>
    public static readonly List<ColorInfo> Horns = new()
    {
        new ColorInfo(){ Name="Truck", Value=1 },
        new ColorInfo(){ Name="Cop Buzzer", Value=2 },
        new ColorInfo(){ Name="Clown", Value=3 },
        new ColorInfo(){ Name="Musical Horn 1", Value=4 },
        new ColorInfo(){ Name="Musical Horn 2", Value=5 },
        new ColorInfo(){ Name="Musical Horn 3", Value=6 },
        new ColorInfo(){ Name="Musical Horn 4", Value=7 },
        new ColorInfo(){ Name="Musical Horn 5", Value=8 },
        new ColorInfo(){ Name="Sad Trombone", Value=9 },
        new ColorInfo(){ Name="Classical Horn 1", Value=10 },
        new ColorInfo(){ Name="Classical Horn 2", Value=11 },
        new ColorInfo(){ Name="Classical Horn 3", Value=12 },
        new ColorInfo(){ Name="Classical Horn 4", Value=13 },
        new ColorInfo(){ Name="Classical Horn 5", Value=14 },
        new ColorInfo(){ Name="Classical Horn 6", Value=15 },
        new ColorInfo(){ Name="Classical Horn 7", Value=16 },
        new ColorInfo(){ Name="Do", Value=17 },
        new ColorInfo(){ Name="Re", Value=18 },
        new ColorInfo(){ Name="Mi", Value=19 },
        new ColorInfo(){ Name="Fa", Value=20 },
        new ColorInfo(){ Name="So", Value=21 },
        new ColorInfo(){ Name="La", Value=22 },
        new ColorInfo(){ Name="Ti", Value=23 },
        new ColorInfo(){ Name="Do (High)", Value=24 },
        new ColorInfo(){ Name="Jazz Horn 1", Value=25 },
        new ColorInfo(){ Name="Jazz Horn 2", Value=26 },
        new ColorInfo(){ Name="Jazz Horn 3", Value=27 },
        new ColorInfo(){ Name="Jazz Horn Loop", Value=28 },
        new ColorInfo(){ Name="Star Spangled 1", Value=29 },
        new ColorInfo(){ Name="Star Spangled 2", Value=30 },
        new ColorInfo(){ Name="Star Spangled 3", Value=31 },
        new ColorInfo(){ Name="Star Spangled 4", Value=32 },
        new ColorInfo(){ Name="Classical Horn Loop 1", Value=33 },
        new ColorInfo(){ Name="Classical Horn 8", Value=34 },
        new ColorInfo(){ Name="Classical Horn Loop 2", Value=35 },
        new ColorInfo(){ Name="Halloween 1", Value=39 },
        new ColorInfo(){ Name="Halloween 2", Value=40 },
        new ColorInfo(){ Name="Halloween 3", Value=42 },
        new ColorInfo(){ Name="San Andreas Loop", Value=43 },
        new ColorInfo(){ Name="Liberty City Loop", Value=46 },
        new ColorInfo(){ Name="Jingle Bells", Value=47 },
        new ColorInfo(){ Name="Sleigh Bells", Value=48 },
        new ColorInfo(){ Name="Deck the Halls", Value=49 },
        new ColorInfo(){ Name="Sleigh Bells Loop", Value=50 },
        new ColorInfo(){ Name="Organ Song", Value=51 },
        new ColorInfo(){ Name="Air Horn 1", Value=53 },
        new ColorInfo(){ Name="Short Air Horn 1", Value=54 },
        new ColorInfo(){ Name="Air Horn 2", Value=55 },
        new ColorInfo(){ Name="Short Air Horn 2", Value=56 },
        new ColorInfo(){ Name="Air Horn 3", Value=57 },
        new ColorInfo(){ Name="Short Air Horn 3", Value=58 },
    };
}